adding some safety features

diff --git a/bin/dealerd b/bin/dealerd
--- a/bin/dealerd
+++ b/bin/dealerd
@@ -28,6 +28,15 @@ do
   echo "Start $RUNS_PER_CYCLE loops; log file $LOG" >> $LOG
   $DYNAMO_BASE/bin/dealer --log-level INFO --log-file $LOG --repeat $RUNS_PER_CYCLE $DYNAMO_DEALER_INTERVAL 2>>$LOG
 
+  if [ $? -ne 0 ]
+  then
+    # execution failed - recover inventory to avoid running with corrupt inventory
+    $DYNAMO_BASE/bin/execlib common/interface/store.py restore --timestamp last
+    $DYNAMO_BASE/bin/execlib common/interface/store.py set_last_update 0
+    # and send email
+    echo "Help! Detox failed - check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+  fi
+
   # take a deep breath
   sleep 5
 
