signal handling

diff --git a/bin/dealerd b/bin/dealerd
--- a/bin/dealerd
+++ b/bin/dealerd
@@ -27,14 +27,20 @@ do
 
   echo "Start $RUNS_PER_CYCLE loops; log file $LOG" >> $LOG
   $DYNAMO_BASE/bin/dealer --log-level INFO --log-file $LOG --repeat $RUNS_PER_CYCLE $DYNAMO_DEALER_INTERVAL 2>>$LOG
+  RC=$?
 
-  if [ $? -ne 0 ]
+  if [ $RC -ne 0 ]
   then
     # execution failed - recover inventory to avoid running with corrupt inventory
     $DYNAMO_BASE/bin/execlib common/interface/store.py restore --timestamp last
     $DYNAMO_BASE/bin/execlib common/interface/store.py set_last_update 0
-    # and send email
-    echo "Help! Detox failed - check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+    if [ -e /var/run/dynamo-dealerd.pid ]
+    then
+      # this process is run as a daemon - send email and continue
+      echo "Help! Dealer failed. Return code $RC. Check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+    else
+      exit $RC 
+    fi
   fi
 
   # take a deep breath
diff --git a/bin/detoxd b/bin/detoxd
--- a/bin/detoxd
+++ b/bin/detoxd
@@ -10,7 +10,7 @@ RUNS_PER_CYCLE=10
 export DYNAMO_BASE=$(dirname $(cd $(dirname ${BASH_SOURCE[0]}); pwd))
 source $DYNAMO_BASE/etc/profile.d/init.sh
 
-while [ 1 ]
+while true
 do
 
   # make sure the log directory exists
@@ -27,14 +27,20 @@ do
 
   echo "Start $RUNS_PER_CYCLE loops; log file $LOG" >> $LOG
   $DYNAMO_BASE/bin/detox --test-run --log-level INFO --log-file $LOG --repeat $RUNS_PER_CYCLE $DYNAMO_DETOX_INTERVAL 2>>$LOG
+  RC=$?
 
-  if [ $? -ne 0 ]
+  if [ $RC -ne 0 ]
   then
     # execution failed - recover inventory to avoid running with corrupt inventory
     $DYNAMO_BASE/bin/execlib common/interface/store.py restore --timestamp last
     $DYNAMO_BASE/bin/execlib common/interface/store.py set_last_update 0
-    # and send email
-    echo "Help! Detox failed - check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+    if [ -e /var/run/dynamo-detoxd.pid ]
+    then
+      # this process is run as a daemon - send email and continue
+      echo "Help! Detox failed. Return code $RC. Check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+    else
+      exit $RC 
+    fi
   fi
 
   # take a deep breath
