changed executables behaviors

diff --git a/bin/dynamod b/bin/dynamod
--- a/bin/dynamod
+++ b/bin/dynamod
@@ -18,6 +18,7 @@ do
 done
 
 HOURS_PER_LOGFILE=12
+INVENTORY_UPDATE_INTERVAL=6
 
 export DYNAMO_BASE=$(dirname $(cd $(dirname ${BASH_SOURCE[0]}); pwd))
 source $DYNAMO_BASE/etc/profile.d/init.sh
@@ -41,111 +42,112 @@ do
   fi
 
   echo "Start $HOURS_PER_LOGFILE cycles; log file $LOG"
+  echo ""
+
   IHOUR=0
   while [ $IHOUR -lt $HOURS_PER_LOGFILE ]
   do
-    OPTIONS=""
     APPLICATIONS=""
     if [ $(($IHOUR%$DYNAMO_DETOX_INTERVAL)) -eq 0 ]
     then
       APPLICATIONS="detox"
-      OPTIONS=$OPTIONS" --force-inventory-update"
     fi
     if [ $(($IHOUR%$DYNAMO_DEALER_INTERVAL)) -eq 0 ]
     then
       APPLICATIONS="dealer $APPLICATIONS"
     fi
 
+    if [ $(($IHOUR%$INVENTORY_UPDATE_INTERVAL)) -eq 0 ]
+    then
+      echo "Updating the inventory."
+      $DYNAMO_BASE/bin/execlib common/inventory.py update --no-snapshot
+    fi
+
     IHOUR=$(($IHOUR+1))
 
-    if [ -z "$APPLICATIONS" ]
+    if [ "$APPLICATIONS" ]
     then
-      sleep 3600
-      continue
-    fi
+      date
 
-    date
-
-    $DYNAMO_BASE/bin/execlib common/interface/history.py snapshot
-
-    $DYNAMO_BASE/bin/dynamo $APPLICATIONS $OPTIONS $TEST --log-level INFO
-    RC=$?
-
-    if [ $RC -ne 0 ] && [ $RC -ne 130 ]
-    then
-      # this is a crash of some sort
-      TAG=crash_$(date +%s)
-      echo "Abnormal termination of dynamo cycle. Preserving the database state to tag $TAG."
-      $DYNAMO_BASE/bin/execlib common/interface/store.py snapshot --tag $TAG
-      $DYNAMO_BASE/bin/execlib common/interface/history.py snapshot $TAG
-      echo "Restoring the database state."
-      $DYNAMO_BASE/bin/execlib common/interface/store.py restore --tag last
-      $DYNAMO_BASE/bin/execlib common/interface/store.py set_last_update 0
-      $DYNAMO_BASE/bin/execlib common/interface/history.py restore last
-
-      if [ -e /var/run/dynamod.pid ]
+      echo "Taking a snapshot of the history DB."
+      $DYNAMO_BASE/bin/execlib common/interface/history.py snapshot
+  
+      echo "Starting the main program."
+      $DYNAMO_BASE/bin/dynamo $APPLICATIONS $TEST --log-level INFO
+      RC=$?
+  
+      if [ $RC -ne 0 ] && [ $RC -ne 130 ]
       then
-        # this process is run as a daemon - send email and continue
-        echo "Help! Dynamo failed. Return code $RC. Check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
-
-        if [ $($DYNAMO_BASE/bin/execlib common/interface/store.py list snapshots | grep crash | wc -l) -ge 2 ]
+        # this is a crash of some sort
+        TAG=crash_$(date +%s)
+        echo "Abnormal termination of dynamo cycle. Preserving the history state to tag $TAG."
+        $DYNAMO_BASE/bin/execlib common/interface/history.py snapshot $TAG
+        echo "Restoring the history database."
+        $DYNAMO_BASE/bin/execlib common/interface/history.py restore last
+  
+        if [ -e /var/run/dynamod.pid ]
         then
-          echo "Two crash snapshots found. Likely this is a systematic problem. Exiting with code $RC."
+          # this process is run as a daemon - send email and continue
+          echo "Help! Dynamo failed. Return code $RC. Check log $LOG on $HOSTNAME." | mailx -s "Dynamo error" t2lab@mit.edu
+  
+          if [ $($DYNAMO_BASE/bin/execlib common/interface/store.py list snapshots | grep crash | wc -l) -ge 2 ]
+          then
+            echo "Two crash snapshots found. Likely this is a systematic problem. Exiting with code $RC."
+            exit $RC
+          fi
+  
+          echo "Re-entering cycle.. (see next log)"
+          break
+        else
+          echo "Exiting with code $RC."
           exit $RC
         fi
-
-        echo "Re-entering cycle.. (see next log)"
-        break
-      else
-        echo "Exiting with code $RC."
-        exit $RC
       fi
-    fi
-
-    if ! [ "$TEST" ] && [[ $APPLICATIONS =~ detox ]]
-    then
-      # test run to produce sites info
-      if ! [ -e /var/run/dynamod.pid ]
-      then
-        # this is a non-daemon execution (test run?) - we need to set a comment
-        COMMENT='--comment "Test run under command line execution."'
-      fi
-      $DYNAMO_BASE/bin/dynamo detox --test-run --detox-partition 'DataOps' 'caf-comm:MinimumCopies' 'caf-alca:MinimumCopies' 'local:MinimumCopies' 'IB RelVal:MinimumCopies' --log-level INFO $COMMENT
-    fi
-
-    if [ $IHOUR -eq $HOURS_PER_LOGFILE ]
-    then
-      # Clean unsubscribed data once every HOURS_PER_LOGFILE cycles
-      $DYNAMO_BASE/bin/dynamo detox $TEST --detox-partition 'Unsubscribed' --log-level INFO
-    fi
-
-    $DYNAMO_BASE/bin/execlib common/interface/history.py clean last
-
-    if [ $RC -eq 130 ]
-    then
-      # case: dynamo killed with SIGINT - you were probably running this script in a terminal and pressed Ctrl-C
-      exit 0
-    fi
-
-    if ! [ "$TEST" ]
-    then
-      $DYNAMO_BASE/bin/siteinfo --out /home/$USER/public_html/IntelROCCS/Detox
-    fi
   
-    echo ""
-
-    if [ "$TEST" ]
-    then
-      echo "Exiting from test run."
-      exit 0
+      if ! [ "$TEST" ] && [[ $APPLICATIONS =~ detox ]] && [ $RC -ne 130 ]
+      then
+        # test run to produce sites info
+        if ! [ -e /var/run/dynamod.pid ]
+        then
+          # this is a non-daemon execution (test run?) - we need to set a comment
+          COMMENT='--comment "Test run under command line execution."'
+        fi
+        $DYNAMO_BASE/bin/dynamo detox --test-run --detox-partition 'DataOps' 'caf-comm:MinimumCopies' 'caf-alca:MinimumCopies' 'local:MinimumCopies' 'IB RelVal:MinimumCopies' --log-level INFO $COMMENT
+      fi
+  
+      if [ $IHOUR -eq $HOURS_PER_LOGFILE ] && [ $RC -ne 130 ]
+      then
+        # Clean unsubscribed data once every HOURS_PER_LOGFILE cycles
+        $DYNAMO_BASE/bin/dynamo detox $TEST --detox-partition 'Unsubscribed' --log-level INFO
+      fi
+  
+      $DYNAMO_BASE/bin/execlib common/interface/history.py clean last
+  
+      if [ $RC -eq 130 ]
+      then
+        # case: dynamo killed with SIGINT - you were probably running this script in a terminal and pressed Ctrl-C
+        exit 0
+      fi
+  
+      if ! [ "$TEST" ]
+      then
+        $DYNAMO_BASE/bin/siteinfo --out /home/$USER/public_html/IntelROCCS/Detox
+      fi
+    
+      echo ""
     fi
 
     sleep 3600
   done
 
+  if [ "$TEST" ]
+  then
+    echo "Exiting from test run."
+    break
+  fi
+
   # take a deep breath
   sleep 5
-
 done
 
 exit 0
